#
 # FreeBSD system call object files.
 #
 # DO NOT EDIT-- this file is automatically @generated.
 #

MIASM =  \
	read.o \
	write.o \
	linux_open.o \
	close.o \
	linux_newstat.o \
	linux_newfstat.o \
	linux_newlstat.o \
	linux_poll.o \
	linux_lseek.o \
	linux_mmap2.o \
	linux_mprotect.o \
	munmap.o \
	linux_brk.o \
	linux_rt_sigaction.o \
	linux_rt_sigprocmask.o \
	linux_rt_sigreturn.o \
	linux_ioctl.o \
	linux_pread.o \
	linux_pwrite.o \
	readv.o \
	writev.o \
	linux_access.o \
	linux_pipe.o \
	linux_select.o \
	sched_yield.o \
	linux_mremap.o \
	linux_msync.o \
	linux_mincore.o \
	linux_madvise.o \
	linux_shmget.o \
	linux_shmat.o \
	linux_shmctl.o \
	dup.o \
	dup2.o \
	linux_pause.o \
	linux_nanosleep.o \
	linux_getitimer.o \
	linux_alarm.o \
	linux_setitimer.o \
	linux_getpid.o \
	linux_sendfile.o \
	linux_socket.o \
	linux_connect.o \
	linux_accept.o \
	linux_sendto.o \
	linux_recvfrom.o \
	linux_sendmsg.o \
	linux_recvmsg.o \
	linux_shutdown.o \
	linux_bind.o \
	linux_listen.o \
	linux_getsockname.o \
	linux_getpeername.o \
	linux_socketpair.o \
	linux_setsockopt.o \
	linux_getsockopt.o \
	linux_clone.o \
	linux_fork.o \
	linux_vfork.o \
	linux_execve.o \
	linux_exit.o \
	linux_wait4.o \
	linux_kill.o \
	linux_newuname.o \
	linux_semget.o \
	semop.o \
	linux_semctl.o \
	linux_shmdt.o \
	linux_msgget.o \
	linux_msgsnd.o \
	linux_msgrcv.o \
	linux_msgctl.o \
	linux_fcntl.o \
	flock.o \
	fsync.o \
	linux_fdatasync.o \
	linux_truncate.o \
	linux_ftruncate.o \
	linux_getdents.o \
	linux_getcwd.o \
	linux_chdir.o \
	fchdir.o \
	linux_rename.o \
	linux_mkdir.o \
	linux_rmdir.o \
	linux_creat.o \
	linux_link.o \
	linux_unlink.o \
	linux_symlink.o \
	linux_readlink.o \
	linux_chmod.o \
	fchmod.o \
	linux_chown.o \
	fchown.o \
	linux_lchown.o \
	umask.o \
	gettimeofday.o \
	linux_getrlimit.o \
	getrusage.o \
	linux_sysinfo.o \
	linux_times.o \
	linux_ptrace.o \
	linux_getuid.o \
	linux_syslog.o \
	linux_getgid.o \
	setuid.o \
	setgid.o \
	geteuid.o \
	getegid.o \
	setpgid.o \
	linux_getppid.o \
	getpgrp.o \
	setsid.o \
	setreuid.o \
	setregid.o \
	linux_getgroups.o \
	linux_setgroups.o \
	setresuid.o \
	getresuid.o \
	setresgid.o \
	getresgid.o \
	getpgid.o \
	linux_setfsuid.o \
	linux_setfsgid.o \
	linux_getsid.o \
	linux_capget.o \
	linux_capset.o \
	linux_rt_sigpending.o \
	linux_rt_sigtimedwait.o \
	linux_rt_sigqueueinfo.o \
	linux_rt_sigsuspend.o \
	linux_sigaltstack.o \
	linux_utime.o \
	linux_mknod.o \
	linux_personality.o \
	linux_ustat.o \
	linux_statfs.o \
	linux_fstatfs.o \
	linux_sysfs.o \
	linux_getpriority.o \
	setpriority.o \
	linux_sched_setparam.o \
	linux_sched_getparam.o \
	linux_sched_setscheduler.o \
	linux_sched_getscheduler.o \
	linux_sched_get_priority_max.o \
	linux_sched_get_priority_min.o \
	linux_sched_rr_get_interval.o \
	mlock.o \
	munlock.o \
	mlockall.o \
	munlockall.o \
	linux_vhangup.o \
	linux_modify_ldt.o \
	linux_pivot_root.o \
	linux_sysctl.o \
	linux_prctl.o \
	linux_arch_prctl.o \
	linux_adjtimex.o \
	linux_setrlimit.o \
	chroot.o \
	sync.o \
	acct.o \
	settimeofday.o \
	linux_mount.o \
	linux_umount.o \
	swapon.o \
	linux_swapoff.o \
	linux_reboot.o \
	linux_sethostname.o \
	linux_setdomainname.o \
	linux_iopl.o \
	linux_ioperm.o \
	linux_init_module.o \
	linux_delete_module.o \
	linux_quotactl.o \
	linux_gettid.o \
	linux_readahead.o \
	linux_setxattr.o \
	linux_lsetxattr.o \
	linux_fsetxattr.o \
	linux_getxattr.o \
	linux_lgetxattr.o \
	linux_fgetxattr.o \
	linux_listxattr.o \
	linux_llistxattr.o \
	linux_flistxattr.o \
	linux_removexattr.o \
	linux_lremovexattr.o \
	linux_fremovexattr.o \
	linux_tkill.o \
	linux_time.o \
	linux_sys_futex.o \
	linux_sched_setaffinity.o \
	linux_sched_getaffinity.o \
	linux_io_setup.o \
	linux_io_destroy.o \
	linux_io_getevents.o \
	linux_io_submit.o \
	linux_io_cancel.o \
	linux_lookup_dcookie.o \
	linux_epoll_create.o \
	linux_remap_file_pages.o \
	linux_getdents64.o \
	linux_set_tid_address.o \
	linux_restart_syscall.o \
	linux_semtimedop.o \
	linux_fadvise64.o \
	linux_timer_create.o \
	linux_timer_settime.o \
	linux_timer_gettime.o \
	linux_timer_getoverrun.o \
	linux_timer_delete.o \
	linux_clock_settime.o \
	linux_clock_gettime.o \
	linux_clock_getres.o \
	linux_clock_nanosleep.o \
	linux_exit_group.o \
	linux_epoll_wait.o \
	linux_epoll_ctl.o \
	linux_tgkill.o \
	linux_utimes.o \
	linux_mbind.o \
	linux_set_mempolicy.o \
	linux_get_mempolicy.o \
	linux_mq_open.o \
	linux_mq_unlink.o \
	linux_mq_timedsend.o \
	linux_mq_timedreceive.o \
	linux_mq_notify.o \
	linux_mq_getsetattr.o \
	linux_kexec_load.o \
	linux_waitid.o \
	linux_add_key.o \
	linux_request_key.o \
	linux_keyctl.o \
	linux_ioprio_set.o \
	linux_ioprio_get.o \
	linux_inotify_init.o \
	linux_inotify_add_watch.o \
	linux_inotify_rm_watch.o \
	linux_migrate_pages.o \
	linux_openat.o \
	linux_mkdirat.o \
	linux_mknodat.o \
	linux_fchownat.o \
	linux_futimesat.o \
	linux_newfstatat.o \
	linux_unlinkat.o \
	linux_renameat.o \
	linux_linkat.o \
	linux_symlinkat.o \
	linux_readlinkat.o \
	linux_fchmodat.o \
	linux_faccessat.o \
	linux_pselect6.o \
	linux_ppoll.o \
	linux_unshare.o \
	linux_set_robust_list.o \
	linux_get_robust_list.o \
	linux_splice.o \
	linux_tee.o \
	linux_sync_file_range.o \
	linux_vmsplice.o \
	linux_move_pages.o \
	linux_utimensat.o \
	linux_epoll_pwait.o \
	linux_signalfd.o \
	linux_timerfd_create.o \
	linux_eventfd.o \
	linux_fallocate.o \
	linux_timerfd_settime.o \
	linux_timerfd_gettime.o \
	linux_accept4.o \
	linux_signalfd4.o \
	linux_eventfd2.o \
	linux_epoll_create1.o \
	linux_dup3.o \
	linux_pipe2.o \
	linux_inotify_init1.o \
	linux_preadv.o \
	linux_pwritev.o \
	linux_rt_tgsigqueueinfo.o \
	linux_perf_event_open.o \
	linux_recvmmsg.o \
	linux_fanotify_init.o \
	linux_fanotify_mark.o \
	linux_prlimit64.o \
	linux_name_to_handle_at.o \
	linux_open_by_handle_at.o \
	linux_clock_adjtime.o \
	linux_syncfs.o \
	linux_sendmmsg.o \
	linux_setns.o \
	linux_getcpu.o \
	linux_process_vm_readv.o \
	linux_process_vm_writev.o \
	linux_kcmp.o \
	linux_finit_module.o \
	linux_sched_setattr.o \
	linux_sched_getattr.o \
	linux_renameat2.o \
	linux_seccomp.o \
	linux_getrandom.o \
	linux_memfd_create.o \
	linux_kexec_file_load.o \
	linux_bpf.o \
	linux_execveat.o \
	linux_userfaultfd.o \
	linux_membarrier.o \
	linux_mlock2.o \
	linux_copy_file_range.o \
	linux_preadv2.o \
	linux_pwritev2.o \
	linux_pkey_mprotect.o \
	linux_pkey_alloc.o \
	linux_pkey_free.o \
	linux_statx.o \
	linux_io_pgetevents.o \
	linux_rseq.o \
	linux_pidfd_send_signal.o \
	linux_io_uring_setup.o \
	linux_io_uring_enter.o \
	linux_io_uring_register.o \
	linux_open_tree.o \
	linux_move_mount.o \
	linux_fsopen.o \
	linux_fsconfig.o \
	linux_fsmount.o \
	linux_fspick.o \
	linux_pidfd_open.o \
	linux_clone3.o \
	linux_close_range.o \
	linux_openat2.o \
	linux_pidfd_getfd.o \
	linux_faccessat2.o \
	linux_process_madvise.o \
	linux_epoll_pwait2.o \
	linux_mount_setattr.o \
